<!DOCTYPE html>
<html lang="pt-br">
    <head>
    
        <meta charset="utf-8">

    </head>

    <body>
        <script src="../../libs/js/jquery.min.js"></script>
        <script src="../../libs/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="../../libs/mysheets/style.css">
        <link rel="stylesheet" href="../../libs/fonts/material-icon.css">
        <link rel="stylesheet" href="../../libs/stylesheets/bootstrap.min.css">
        
        <?php require_once __DIR__ . "/header.phtml" ?>

        <?php $this->conteudoView() ?>

        <?php require_once __DIR__ . "/footer.phtml" ?>

    </body>
</html>