

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
function findMission() {
    id = document.getElementById('idToFind').value
    $.ajax({
        url:'/mission/' + id + '/buscar',
        complete: function (response) {
            result = response.responseText
            if (!result) {
                alert('Invalid ID!')
                document.getElementById('idToFind').value = ''
                return
            }
            result = JSON.parse(result)

            document.getElementById('missionID').value = result['missionid']
            document.getElementById('name').value = result['name']
            document.getElementById('description').value = result['description']
        },
        error: function () {
            alert('Erro')
        }
    })

    return false
}
</script>

<?php
// MENSAGEM DE CADASTRADO
if (isset($_GET['cadastrado'])) {
    $status = "danger";
    $mensagem = "Falha ao inserir registro";
    if ($_GET['cadastrado']) {
        $status = "success";
        $mensagem = "Registro inserido com sucesso";
    }
    ?>
    <div class="alert alert-dismissible alert-<?= $status ?>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?= $mensagem ?>
    </div>
<?php } ?>


<div class="container">
<br><h1>Mission</h1><br>

<form action="/mission/inserir" method="POST">

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="">Mission ID to find:</label>
            <input type="text" id="idToFind" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <button type="button" class="btn btn-sm btn-success" style="margin-top: 35px;" onClick="return findMission();"><i class='fa fa-check-circle'></i> Find Mission</button>
        </div>
    </div><br>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="missionID">Mission ID</label>
            <input type="text" class="form-control" id="missionID" name="missionID" placeholder="Mission ID" readonly>
        </div>
        <div class="form-group col-md-6">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name" readonly>
        </div>
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea style="resize:none" class="form-control" rows="5" id="description" name="description" placeholder="Description" readonly></textarea>
    </div>

    <button type="submit" class="btn btn-sm btn-primary float-right"><i class='fa fa-plus-circle'></i> Adicionar</button>
</form>

</div><br><br><br><br>