

<div class="table-wrapper">

<div class="table-title">
    <div class="row">
        <div class="col-sm-6">
            <h2>Missions</h2>
        </div>
    </div>
</div>


<table class="table table-striped table-hover">

    <thead>
        <tr>
            <th>ID</th>
            <th>Mission ID</th>
            <th>Name</th>
            <th>Description</th>   
        </tr>
    </thead>

    <tbody>
    <?php foreach ($this->view->missions as $mission): ?>
        <tr>
            <td><?php echo $mission->getId(); ?></td>
            <td><?php echo $mission->getMissionId(); ?></td>
            <td><?php echo $mission->getName(); ?></td>
            <td><?php echo $mission->getDescription(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>

</div>

