

<div class="table-wrapper">


<table class="table table-striped table-hover">

    <thead>
        <tr>
            <th>ID</th>
            <th>Mission ID</th>
            <th>Name</th>
            <th>Description</th>   
        </tr>
    </thead>

    <tbody>
    <?php foreach ($this->view->missions as $mission): ?>
    <tr onclick="location.href = '/mission/<?php echo $mission->getMissionId(); ?>/visualizar';" style="cursor: pointer;">
            <td><?php echo $mission->getId(); ?></td>
            <td><?php echo $mission->getMissionId(); ?></td>
            <td><?php echo $mission->getName(); ?></td>
            <td><?php echo $mission->getDescription(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>

</div>

