

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
function findRocket() {
    id = document.getElementById('idToFind').value
    $.ajax({
        url:'/rocket/' + id + '/buscar',
        complete: function (response) {
            result = response.responseText
            result = JSON.parse(result)

            document.getElementById('rocketID').value = result['rocketid']
            document.getElementById('name').value = result['name']
            document.getElementById('description').value = result['description']
            document.getElementById('firstFlight').value = result['firstflight']
            document.getElementById('height').value = result['height']
            document.getElementById('diameter').value = result['diameter']
            document.getElementById('mass').value = result['mass']
            document.getElementById('image').value = result['image']
        },
        error: function () {
            alert('Erro')
        }
    })

    return false
}
</script>

<?php
// MENSAGEM DE CADASTRADO
if (isset($_GET['cadastrado'])) {
    $status = "danger";
    $mensagem = "Falha ao inserir registro";
    if ($_GET['cadastrado']) {
        $status = "success";
        $mensagem = "Registro inserido com sucesso";
    }
    ?>
    <div class="alert alert-dismissible alert-<?= $status ?>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?= $mensagem ?>
    </div>
<?php } ?>


<div class="container">
<br><h1>Rocket</h1><br>

<form action="/rocket/inserir" method="POST">

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="">Rocket ID to find:</label>
            <input type="text" id="idToFind" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <button type="button" class="btn btn-sm btn-success" style="margin-top: 35px;" onClick="return findRocket();"><i class='fa fa-check-circle'></i> Find Rocket</button>
        </div>
    </div><br>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="rocketID">Rocket ID</label>
            <input type="text" class="form-control" id="rocketID" name="rocketID" placeholder="Rocket ID" readonly>
        </div>
        <div class="form-group col-md-6">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name" readonly>
        </div>
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea style="resize:none" class="form-control" rows="3" id="description" name="description" placeholder="Description" readonly></textarea>
    </div>
    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="firstFlight">First Flight</label>
            <input type="date" class="form-control" id="firstFlight" name="firstFlight" placeholder="First Flight" readonly>
        </div>
        <div class="form-group col-md-3">
            <label for="height">Height (m)</label>
            <input type="number" class="form-control" id="height" name="height" placeholder="Height" readonly>
        </div>
        <div class="form-group col-md-3">
            <label for="diameter">Diameter (m)</label>
            <input type="number" class="form-control" id="diameter" name="diameter" placeholder="Diameter" readonly>
        </div>
        <div class="form-group col-md-3">
            <label for="mass">Mass (kg)</label>
            <input type="number" class="form-control" id="mass" name="mass" placeholder="Mass" readonly>
        </div>
    </div>
    <div class="form-group">
        <label for="image">Image</label>
        <input type="text" class="form-control" id="image" name="image" placeholder="Image" readonly>
    </div>

    <button type="submit" class="btn btn-sm btn-primary float-right"><i class='fa fa-plus-circle'></i> Adicionar</button>
</form>

</div><br><br><br><br>