

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
function findLaunch() {
    id = document.getElementById('idToFind').value
    $.ajax({
        url:'/launch/' + id + '/buscar',
        complete: function (response) {
            result = response.responseText
            if (!result) {
                alert('Invalid Flight Number!')
                document.getElementById('idToFind').value = ''
                return
            }
            result = JSON.parse(result)

            document.getElementById('flightNumber').value = result['flightnumber']
            document.getElementById('date').value = result['date']
            document.getElementById('rocketID').value = result['objectrocket']['rocketid']
            document.getElementById('missionID').value = (result['objectmission'] ? result['objectmission']['missionid'] : null)
            document.getElementById('description').value = result['description']
            document.getElementById('image').value = result['image']
        },
        error: function () {
            alert('Erro')
        }
    })

    return false
}
</script>

<?php
// MENSAGEM DE CADASTRADO
if (isset($_GET['cadastrado'])) {
    $status = "danger";
    $mensagem = "Falha ao inserir registro";
    if ($_GET['cadastrado']) {
        $status = "success";
        $mensagem = "Registro inserido com sucesso";
    }
    ?>
    <div class="alert alert-dismissible alert-<?= $status ?>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?= $mensagem ?>
    </div>
<?php } ?>


<div class="container">
<br><h1>Launch</h1><br>

<form action="/launch/inserir" method="POST">

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="">Flight Number to find:</label>
            <input type="number" id="idToFind" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <button type="button" class="btn btn-sm btn-success" style="margin-top: 35px;" onClick="return findLaunch();"><i class='fa fa-check-circle'></i> Find Launch</button>
        </div>
    </div><br>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="flightNumber">Flight Number</label>
            <input type="text" class="form-control" id="flightNumber" name="flightNumber" placeholder="Flight Number" readonly>
        </div>
        <div class="form-group col-md-3">
            <label for="date">Date</label>
            <input type="date" class="form-control" id="date" name="date" placeholder="Date" readonly>
        </div>
        <div class="form-group col-md-3">
            <label for="rocketID">Rocket ID</label>
            <input type="text" class="form-control" id="rocketID" name="rocketID" placeholder="Rocket ID" readonly>
        </div>
        <div class="form-group col-md-3">
            <label for="missionID">Mission ID</label>
            <input type="text" class="form-control" id="missionID" name="missionID" placeholder="Mission ID" readonly>
        </div>
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea style="resize:none" class="form-control" rows="5" id="description" name="description" placeholder="Description" readonly></textarea>
    </div>
    <div class="form-group">
        <label for="image">Image</label>
        <input type="text" class="form-control" id="image" name="image" placeholder="Image" readonly>
    </div>

    <button type="submit" class="btn btn-sm btn-primary float-right"><i class='fa fa-plus-circle'></i> Adicionar</button>
</form>

</div><br><br><br><br>