

<div class="table-wrapper">

<table class="table table-striped table-hover">

    <thead>
        <tr>
            <th>ID</th>
            <th>Flight Number</th>
            <th>Date</th>
            <th>Rocket ID</th>   
            <th>Mission ID</th>
            <th>Description</th>
        </tr>
    </thead>

    <tbody>
    <?php foreach ($this->view->launches as $launch): ?>
        <tr>
            <td><?php echo $launch->getId(); ?></td>
            <td><?php echo $launch->getFlightNumber(); ?></td>
            <td><?php echo $launch->getDate(); ?></td>
            <td><?php echo $launch->getRocket()->getRocketId(); ?></td>
            <td><?php echo $launch->getMission()->getMissionId(); ?></td>
            <td style="width: 700px;"><?php echo $launch->getDescription(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>

</div>

