

<div class="container">
<br><h1>Launch</h1><br>

<div class="form-row">
    <div class="form-group col-md-3">
        <label for="flightNumber">Flight Number</label>
        <input type="text" class="form-control" value="<?= $this->view->launch->getFlightNumber() ?>" id="flightNumber" name="flightNumber" placeholder="Flight Number" readonly>
    </div>
    <div class="form-group col-md-3">
        <label for="date">Date</label>
        <input type="date" class="form-control" value="<?= $this->view->launch->getDate()->format('Y-m-d') ?>" id="date" name="date" placeholder="Date" readonly>
    </div>
    <div class="form-group col-md-3">
        <label for="rocketID">Rocket ID</label>
        <input type="text" class="form-control" value="<?= $this->view->launch->getRocket()->getRocketID() ?>" id="rocketID" name="rocketID" placeholder="Rocket ID" readonly>
    </div>
    <div class="form-group col-md-3">
        <label for="missionID">Mission ID</label>
        <input type="text" class="form-control" value="<?= $this->view->launch->getMission()->getMissionID() ?>" id="missionID" name="missionID" placeholder="Mission ID" readonly>
    </div>
</div>
<div class="form-group">
    <label for="description">Description</label>
    <textarea style="resize:none" class="form-control" rows="5" id="description" name="description" placeholder="Description" readonly><?= $this->view->launch->getDescription() ?></textarea>
</div>
<div class="form-group">
    <label for="image">Image</label>
    <input type="text" class="form-control" value="<?= $this->view->launch->getImage() ?>" id="image" name="image" placeholder="Image" readonly>
</div>

<input type="button" onclick="location.href='/launches';" class="btn btn-sm btn-success float-right" value="Voltar" />
</div><br><br><br><br>