

<?php
// MENSAGEM DE CADASTRADO
if (isset($_GET['cadastrado'])) {
    $status = "danger";
    $mensagem = "Falha ao inserir registro";
    if ($_GET['cadastrado']) {
        $status = "success";
        $mensagem = "Registro inserido com sucesso";
    }
    ?>
    <script type="text/javascript">
        $('#att_Modal').modal('hide')
    </script>  
    <div class="alert alert-dismissible alert-<?= $status ?>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?= $mensagem ?>
    </div>
<?php } ?>


<h2>&nbspCadastro de Produto</h2><br>

<form action="/produto/inserir" method="POST" class="form-horizontal" enctype="multipart/form-data">

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="">Descrição:</label>
            <input type="text" name="descricao" class="form-control" value="" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="">Valor:</label>
            <input type="number" name="valor" class="form-control" value="" step="0.01" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="">Imagem:</label>
            <input type="file" name="imagem" accept="image/*" />
        </div>
    </div>

    <button type="submit" class="btn btn-sm btn-primary pull-right"><i class='fa fa-plus-circle'></i> Adicionar</button>
</form>
