CREATE DATABASE MVC;

USE MVC;

# DROP DATABASE MVC;

CREATE TABLE PRODUTO (
	PRODUTO_CODIGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUTO_DESCRICAO VARCHAR(150) NOT NULL,
    PRODUTO_IMAGEM LONGBLOB,
    PRODUTO_VALOR DOUBLE NOT NULL
);

SELECT * FROM PRODUTO;